import os, pathlib
y = os.getcwd()
print(y)
os.chdir("C:/")
print(os.getcwd())
os.chdir("Program Files (x86)")
os.chdir("Java")
print(os.getcwd())
x = os.getcwd()
os.replace(y + "\\PC_snooper.py", x)